name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase (web + admin + company)
        run: |
          firebase deploy --project tourvoice-prod-425f4 \
            --only "hosting:web,hosting:admin,hosting:company"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
