name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # --- Build Flutter Web (output: build/web) ---
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9" # İstersen versiyonu güncelle
          channel: "stable"

      - name: Build Flutter Web
        run: flutter build web

      # --- Build admin (Vite: admin/dist) ---
      - name: Build admin
        working-directory: admin
        run: npm ci && npm run build

      # --- Build company (Vite: company/dist) ---
      - name: Build company
        working-directory: company
        run: npm ci && npm run build

      # --- Deploy all targets (web + admin + company) ---
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --project tourvoice-prod-425f4 \
            --only "hosting:web,hosting:admin,hosting:company" \
            --token "${{ secrets.FIREBASE_TOKEN }}"
